In [5]:
import numpy as np
import pandas as pd

In [6]:
from google.colab import files
upload = files.upload()

Saving ai_student_impact_dataset (1).csv to ai_student_impact_dataset (1).csv

In [7]:
filepath = '/content/ai_student_impact_dataset (1).csv'
df = pd.read_csv(filepath)

In [8]:
df

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
49999,150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

In [9]:
df.head()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium

In [10]:
df.tail()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
49995,149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
49999,150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  50000 non-null  int64
 1   Major_Category              50000 non-null  object
 2   Year_of_Study               50000 non-null  object
 3   Pre_Semester_GPA            50000 non-null  float64
 4   Weekly_GenAI_Hours          50000 non-null  float64
 5   Primary_Use_Case            50000 non-null  object
 6   Prompt_Engineering_Skill    50000 non-null  object
 7   Tool_Diversity              50000 non-null  int64
 8   Paid_Subscription           50000 non-null  bool
 9   Traditional_Study_Hours     50000 non-null  float64
 10  Perceived_AI_Dependency     50000 non-null  int64
 11  Institutional_Policy        50000 non-null  object
 12  Anxiety_Level_During_Exams  50000 non-null  int64
 13  Post_Semester_GPA           50000 non-null  float64
 14  Skill_Retention_Score       50000 non-null  float64
 15  Burnout_Risk_Level          50000 non-null  object
dtypes: bool(1), float64(5), int64(4), object(6)
memory usage: 5.8+ MB

In [12]:
df.shape

(50000, 16)

In [13]:
df.columns

Index(['Student_ID', 'Major_Category', 'Year_of_Study', 'Pre_Semester_GPA',
       'Weekly_GenAI_Hours', 'Primary_Use_Case', 'Prompt_Engineering_Skill',
       'Tool_Diversity', 'Paid_Subscription', 'Traditional_Study_Hours',
       'Perceived_AI_Dependency', 'Institutional_Policy',
       'Anxiety_Level_During_Exams', 'Post_Semester_GPA',
       'Skill_Retention_Score', 'Burnout_Risk_Level'],
      dtype='object')

In [15]:
df.describe()

,Student_ID,Pre_Semester_GPA,Weekly_GenAI_Hours,Tool_Diversity,Traditional_Study_Hours,Perceived_AI_Dependency,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score
count,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,125000.500000,3.146102,8.427752,2.80026,11.209271,3.505360,4.270760,3.349299,75.798125
std,14433.901067,0.478854,8.269490,1.18802,5.156426,1.820812,2.144066,0.495673,13.281626
min,100001.000000,1.183000,0.000000,1.00000,1.000000,1.000000,1.000000,1.000000,10.780000
25%,112500.750000,2.834000,2.390000,2.00000,7.560000,2.000000,3.000000,3.023750,66.820000
50%,125000.500000,3.210000,5.800000,3.00000,11.180000,3.000000,4.000000,3.421000,76.000000
75%,137500.250000,3.521000,11.720000,4.00000,14.710000,5.000000,6.000000,3.749000,85.190000
max,150000.000000,3.998000,40.000000,5.00000,35.860000,10.000000,10.000000,4.000000,100.000000

In [16]:
df.dtypes

Student_ID                      int64
Major_Category                 object
Year_of_Study                  object
Pre_Semester_GPA              float64
Weekly_GenAI_Hours            float64
Primary_Use_Case               object
Prompt_Engineering_Skill       object
Tool_Diversity                  int64
Paid_Subscription                bool
Traditional_Study_Hours       float64
Perceived_AI_Dependency         int64
Institutional_Policy           object
Anxiety_Level_During_Exams      int64
Post_Semester_GPA             float64
Skill_Retention_Score         float64
Burnout_Risk_Level             object
dtype: object

In [17]:
df.isnull().sum()

Student_ID                    0
Major_Category                0
Year_of_Study                 0
Pre_Semester_GPA              0
Weekly_GenAI_Hours            0
Primary_Use_Case              0
Prompt_Engineering_Skill      0
Tool_Diversity                0
Paid_Subscription             0
Traditional_Study_Hours       0
Perceived_AI_Dependency       0
Institutional_Policy          0
Anxiety_Level_During_Exams    0
Post_Semester_GPA             0
Skill_Retention_Score         0
Burnout_Risk_Level            0
dtype: int64

In [19]:
df.nunique()

Student_ID                    50000
Major_Category                    5
Year_of_Study                     5
Pre_Semester_GPA               2389
Weekly_GenAI_Hours             3566
Primary_Use_Case                  5
Prompt_Engineering_Skill          3
Tool_Diversity                    5
Paid_Subscription                 2
Traditional_Study_Hours        2516
Perceived_AI_Dependency          10
Institutional_Policy              3
Anxiety_Level_During_Exams       10
Post_Semester_GPA              2269
Skill_Retention_Score          5872
Burnout_Risk_Level                3
dtype: int64

In [21]:
df.sample(5)

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
6798,106799,STEM,Freshman,3.274,23.61,Debugging/Troubleshooting,Advanced,3,True,5.30,8,Strict_Ban,10,3.834,80.10,Medium
13531,113532,Humanities,Graduate,3.284,6.16,Debugging/Troubleshooting,Advanced,4,True,7.41,1,Allowed_With_Citation,3,3.665,100.00,Low
17555,117556,STEM,Freshman,2.480,2.76,Debugging/Troubleshooting,Intermediate,4,False,22.27,1,Actively_Encouraged,1,3.007,81.12,Low
20849,120850,STEM,Senior,3.332,10.78,Debugging/Troubleshooting,Beginner,2,True,11.26,4,Allowed_With_Citation,6,3.432,60.23,Low
22137,122138,STEM,Sophomore,3.695,7.73,Debugging/Troubleshooting,Intermediate,1,False,13.91,2,Strict_Ban,5,4.000,78.18,Low

In [22]:
df.value_counts()

Student_ID  Major_Category  Year_of_Study  Pre_Semester_GPA  Weekly_GenAI_Hours  Primary_Use_Case           Prompt_Engineering_Skill  Tool_Diversity  Paid_Subscription  Traditional_Study_Hours  Perceived_AI_Dependency  Institutional_Policy   Anxiety_Level_During_Exams  Post_Semester_GPA  Skill_Retention_Score  Burnout_Risk_Level
149984      Arts            Sophomore      3.245             1.42                Copywriting/Drafting       Beginner                  3               False              10.30                    3                        Actively_Encouraged    4                           3.385              85.93                  Medium                1
149983      Business        Sophomore      3.474             6.68                Direct_Answer_Generation   Intermediate              2               False              7.52                     4                        Allowed_With_Citation  9                           3.507              75.47                  Low                   1
149982      STEM            Graduate       2.256             10.89               Copywriting/Drafting       Advanced                  4               False              10.42                    1                        Allowed_With_Citation  1                           2.450              84.88                  Low                   1
149981      STEM            Graduate       3.419             25.47               Summarizing_Reading        Advanced                  4               True               14.24                    6                        Allowed_With_Citation  7                           3.879              66.16                  High                  1
149980      Business        Senior         3.750             16.00               Ideation                   Beginner                  1               True               7.00                     3                        Allowed_With_Citation  1                           4.000              66.12                  Low                   1
                                                                                                                                                                                                                                                                                                                                             ..
100005      STEM            Sophomore      3.635             9.29                Debugging/Troubleshooting  Advanced                  4               False              12.55                    4                        Allowed_With_Citation  4                           3.798              100.00                 Medium                1
100004      Business        Senior         3.789             1.82                Copywriting/Drafting       Intermediate              4               False              15.23                    2                        Allowed_With_Citation  2                           4.000              63.58                  Medium                1
100003      Business        Freshman       3.398             21.26               Summarizing_Reading        Beginner                  2               False              10.35                    5                        Strict_Ban             9                           3.499              73.93                  Medium                1
100002      Medical         Junior         3.821             1.12                Ideation                   Advanced                  5               False              16.65                    3                        Allowed_With_Citation  9                           3.696              69.39                  Low                   1
100001      Humanities      Senior         2.418             23.31               Copywriting/Drafting       Beginner                  1               True               8.13                     5                        Allowed_With_Citation  6                           2.393              86.44                  High                  1
Name: count, Length: 50000, dtype: int64